version: '3.8'

services:
  angular-build:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      # target: frontend
    container_name: oppia-angular-build
    volumes:
      - .:/app/oppia
      - shared_node_modules:/app/oppia/node_modules
      - shared_third_party:/app/oppia/third_party
      - shared_js_ts_proto_files:/app/oppia/extensions/classifiers/proto
      - shared_assets_dir:/app/oppia/assets
      - shared_angular_build:/app/oppia/dist
    healthcheck:
      test: test "$(ls -A /app/oppia/dist)" || exit 1
      timeout: 30s
      interval: 30s
      retries: 5
      start_period: 5m
    # added max-old-space-size to avoid out of memory error, check this link for more info
    # https://stackoverflow.com/questions/62663167/dockerizing-react-in-production-mode-fatal-error-ineffective-mark-compacts-nea
    command: >
      sh -c '
        trap "rm /app/oppia/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__" EXIT
        export NODE_OPTIONS=--max_old_space_size=4096 && /app/oppia/node_modules/.bin/ng build --watch
      '

  webpack-compiler:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      # target: frontend
    container_name: oppia-webpack-compiler
    volumes:
      - .:/app/oppia
      - shared_node_modules:/app/oppia/node_modules
      - shared_third_party:/app/oppia/third_party
      - shared_js_ts_proto_files:/app/oppia/extensions/classifiers/proto
      - shared_assets_dir:/app/oppia/assets
      - shared_webpack_bundles:/app/oppia/webpack_bundles
    healthcheck:
      test: test "$(ls -A /app/oppia/webpack_bundles)" || exit 1
      timeout: 30s
      interval: 30s
      retries: 5
      start_period: 5m
    entrypoint: node
    command:
      - "/app/oppia/node_modules/webpack/bin/webpack.js"
      - "--config"
      - "/app/oppia/webpack.dev.config.ts"
      - "--watch"
      - "--color"
      - "--progress"

  google-app-engine:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: oppia-app-engine
    ports:
      - "8181:8181"
      - "8000:8000"
    volumes:
      - .:/app/oppia
      - shared_proto_files:/app/oppia/proto_files
      - shared_third_party:/app/oppia/third_party
      - shared_node_modules:/app/oppia/node_modules
      - shared_js_ts_proto_files:/app/oppia/extensions/classifiers/proto
      - shared_assets_dir:/app/oppia/assets
      - shared_angular_build:/app/oppia/dist
      - shared_webpack_bundles:/app/oppia/webpack_bundles
    environment:
      - CLOUDSDK_CORE_DISABLE_PROMPTS=1
      - oppia_is_dockerized=true
    depends_on:
      angular-build:
        condition: service_healthy
      webpack-compiler:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:8181/ || exit 1
      timeout: 10s
      interval: 30s
      retries: 5
      start_period: 7m
    entrypoint: /google-cloud-sdk/bin/dev_appserver.py
    command: 
      - "/app/oppia/app_dev_docker.yaml"
      - "--runtime"
      - "python38"
      - "--host=0.0.0.0"
      - "--port=8181"
      - "--admin_host=0.0.0.0"
      - "--admin_port=8000"
      - "--skip_sdk_update_check=True"

  datastore:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: oppia-cloud-datastore
    ports:
      - "8089:8089"
    environment:
      - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    volumes:
      - cloud_datastore_emulator_cache:/app/cloud_datastore_emulator_cache
    depends_on:
      angular-build:
        condition: service_healthy
      webpack-compiler:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:8089/ || exit 1
      timeout: 10s
      interval: 2m
      retries: 5
      start_period: 7m
    entrypoint: /google-cloud-sdk/bin/gcloud
    command:
      - "beta"
      - "emulators"
      - "datastore"
      - "start"
      - "--project"
      - "dev-project-id"
      - "--data-dir"
      - "/app/cloud_datastore_emulator_cache"
      - "--host-port=0.0.0.0:8089"
      - "--consistency=1.0"
      - "--quiet"
      - "--no-store-on-disk"

  firebase:
    # node:16.13.0
    image: node@sha256:dfa34389d7202cbe7fa82869b9f4c6743c428e8f624136ea8b1783b7aa854fcd
    container_name: oppia-firebase-emulator
    ports:
      - "9099:9099"
      - "4000:4000"
    volumes:
      - ./.firebase.json:/app/oppia/.firebase.json
      - shared_node_modules:/app/oppia/node_modules
      - firebase_emulator_cache:/app/firebase_emulator_cache
    healthcheck:
      test: wget --spider http://localhost:4000/auth/ && echo 'y' | /app/oppia/node_modules/firebase-tools/lib/bin/firebase.js emulators:export /app/firebase_emulator_cache --project=dev-project-id || exit 1
      timeout: 20s
      interval: 20s
      retries: 5
    entrypoint:
      - /app/oppia/node_modules/firebase-tools/lib/bin/firebase.js
      - "emulators:start"
      - "--only"
      - "auth"
      - "--project=dev-project-id"
      - "--config=/app/oppia/.firebase.json"
    command:
      - "--import=/app/firebase_emulator_cache"
      - "--export-on-exit=/app/firebase_emulator_cache"

  redis:
    # redis:6.2.4
    image: redis@sha256:27fd246b9b12b62eeca9f9521ef863278eb11151a5d3d6523c34585fe83df4b3
    container_name: oppia-redis
    ports:
      - "6379:6379"
    environment:
      - PATH=/usr/local/bin/
    volumes:
      - oppia_redis_dump:/app/oppia/dump.db
      - ./redis_docker.conf:/app/oppia/redis_docker.conf
    healthcheck:
      test: redis-cli ping
      timeout: 5s
      interval: 30s
      retries: 5
    command: redis-server /app/oppia/redis_docker.conf

  elasticsearch:
    # elasticsearch:7.17.0
    image: elasticsearch@sha256:fa7141154a7e14df214e42f08c333702403eb88c02ba44e79322a1f42d733013
    container_name: oppia-elasticsearch
    ports:
      - "9200:9200"
    environment:
      - ES_JAVA_OPTS=-Xms100m -Xmx500m
      - ES_PATH_CONF=/usr/share/elasticsearch/config
      - discovery.type=single-node
    depends_on:
      angular-build:
        condition: service_healthy
      webpack-compiler:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:9200/ || exit 1
      timeout: 10s
      interval: 1m
      retries: 5
      start_period: 5m
    command: elasticsearch -q

volumes:
  shared_node_modules:
  shared_proto_files:
  shared_js_ts_proto_files:
  shared_third_party:
  shared_assets_dir:
  shared_angular_build:
  shared_webpack_bundles:
  oppia_redis_dump:
  firebase_emulator_cache:
  cloud_datastore_emulator_cache:
