name: Backend associated test file check
on: [push

jobs:
  run_tests:
    name: Run backend associated test file checks
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.15'
          architecture: 'x64'
      - uses: ./.github/actions/merge
      - name: Initialize Containers
        run: |
          echo ---Initializing containers---
          docker compose up dev-server --no-deps -d
          docker compose up angular-build -d
          echo ---Copying node_modules from container---
          sudo docker cp oppia-angular-build:/app/oppia/node_modules .
      - name: Stop Containers
        run: make stop
      - name: Run backend associated test file check
        run: PYTHONIOENCODING=utf-8 make run_tests.check_backend_associated_tests
      - name: Report failure if failed on oppia/oppia develop branch
        if: ${{ failure() && github.event_name == 'push' && github.repository == 'oppia/oppia' && github.ref == 'refs/heads/develop'}}
        uses: ./.github/actions/send-webhook-notification
        with:
          message: "Some backend files lack an associated test file."
          webhook-url: ${{ secrets.BUILD_FAILURE_ROOM_WEBHOOK_URL }}
