name: Docker Setup Test
on: [push]

jobs:
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - name: Checkout to the Oppia repository code
        uses: actions/checkout@v3

      - name: Start Containers
        run: |
          echo ---Starting containers---
          docker compose up

      - name: Checking server reachability
        run: |
          for i in {1..5}; do
            if curl -s http://localhost:8181/; then
              echo ---Dev-server is up---
              exit 0
            else
              echo ---Retrying in 5mins---
              sleep 300
            fi
          done
          echo ---Dev-server is not started after all retries---
          exit 1
          
      - name: Stop Containers
        run: docker compose down
