name: Custom ESLint tests
on: [push]

jobs:
  run_tests:
    name: Run Tests for Custom ESLint Checks
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.15'
          architecture: 'x64'
      # - uses: ./.github/actions/merge
      # - name: Cache node modules and third_party/static
      #   uses: actions/cache@v3
      #   env:
      #     cache-name: cache-node-modules
      #   with:
      #     path: |
      #       /home/runner/work/oppia/yarn_cache
      #       /home/runner/work/oppia/oppia/third_party/static
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock', 'dependencies.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-
      # - uses: ./.github/actions/install-oppia-dependencies
      # - name: Build Docker Containers
      #   run: |
      #     echo ---Building Docker Images---
      #     docker compose build --no-cache
      - name: Initialize Containers
        run: |
          echo ---Initializing containers---
          docker compose up dev-server --no-deps -d
          docker compose up angular-build -d
          chmod +rwx /home/runner/work/oppia/oppia/node_modules
          docker cp oppia-angular-build:/app/oppia/node_modules .
      - name: Stop Containers
        run: make stop
      - name: Run ESLint Tests
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: PYTHONIOENCODING=utf-8 make run_tests.custom_eslint
      - name: Report failure if failed on oppia/oppia develop branch
        if: ${{ failure() && github.event_name == 'push' && github.repository == 'oppia/oppia' && github.ref == 'refs/heads/develop'}}
        uses: ./.github/actions/send-webhook-notification
        with:
          message: "ESLint checks failed on the upstream develop branch."
          webhook-url: ${{ secrets.BUILD_FAILURE_ROOM_WEBHOOK_URL }}
