name: Install chrome
on: [push]
# on:
#   merge_group:
#     types: [checks_requested]
#   push:
#     branches:
#       - develop
#       - release-*
#   pull_request:
#     branches:
#       - develop
#       - release-*

jobs:
  backend-issue:
    name: Run backend tests
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        shard: [1, 2, 3, 4, 5]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.15'
          architecture: 'x64'
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
      - name: Install packages for optimized coverage
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: sudo apt-get install -y python-dev-is-python3 gcc
      - name: Install coverage and configparser
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: pip install coverage configparser
      - name: Deleting ubuntu files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Initialize Containers
        run: |
          sudo make run-devserver
          make stop
      - name: Run backend test shard
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: PYTHONIOENCODING=utf-8 make run_tests.backend PYTHON_ARGS="--test_target=scripts.check_backend_associated_test_file_test --generate_coverage_report"

  # chrome-workflow:
  #   runs-on:  ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-22.04]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Describe filesystem
  #       run: |
  #         pwd
  #         ls /home/runner/work
  #         ls /home/runner/work/oppia
  #         ls /home/runner/work/oppia/oppia
  #         echo $GITHUB_WORKSPACE
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.8.15'
  #         architecture: 'x64'
  #     - uses: ./.github/actions/merge
  #     - name: Installing chrome
  #       run: |
  #         google-chrome --version
  #         sh .github/install-chrome/install-chrome.sh
  #         google-chrome --version
