name: Install chrome
on: [push]
# on:
#   merge_group:
#     types: [checks_requested]
#   push:
#     branches:
#       - develop
#       - release-*
#   pull_request:
#     branches:
#       - develop
#       - release-*

jobs:
  chrome-workflow:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - name: Describe filesystem
        run: |
          pwd
          ls /home/runner/work
          ls /home/runner/work/oppia
          ls /home/runner/work/oppia/oppia
          echo $GITHUB_WORKSPACE
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.15'
          architecture: 'x64'
      - uses: ./.github/actions/merge
      - uses: nanasess/setup-chromedriver@v2
        with:
          # Optional: do not specify to match Chrome's version
          chromedriver-version: '102.0.5005.61'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - run: google-chrome --version
      - name: Install ffmpeg
        run: sudo apt install ffmpeg
      # Deleting ubuntu files for getting more space (refer: https://github.com/actions/runner-images/issues/2840#issuecomment-1284059930)
      - name: Deleting ubuntu files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Initializing Containers
        run: |
          sudo make build
          sudo docker compose up angular-build -d
          sudo docker cp oppia-angular-build:/app/oppia/node_modules .
      - name: Add permissions to the root oppia folder
        run: sudo chmod -R 777 /home/runner/work/oppia/oppia
      - name: Run E2E Test
        run: sudo xvfb-run -a --server-args="-screen 0, 1285x1000x24" make run_tests.e2e suite=navigation
